name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      # - name: Check style
      #   run: npm run eslint
      - name: Build steps into dist folder
        run: npm run build
      # - name: Test with Jest
      #   run: npm run test
      # - name: e2e tests
      #   uses: cypress-io/github-action@v5
      #   with:
      #     command: npm run test:e2e
      #     start: npm run start-prod
      #     wait-on: http://localhost:5000
      - name: akhileshns/heroku-deploy@v3.12.13 but will not run if it's not a push to main or if \#skip in the commit message
        uses: akhileshns/heroku-deploy@v3.12.13
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        if: ${{ (github.event_name == 'push') && (contains(join(fromJSON(env.COMMIT_MESSAGES)), '#skip') == false) }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "whispering-chamber-99501"
          heroku_email: "hongjinnpark@gmail.com"
          # healthcheck: "https://notes-gha.herokuapp.com/health"
          # checkstring: "healthy"
          # rollbackonhealthcheckfailed: true
